steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$SHORT_SHA
      - ./app
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$SHORT_SHA
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/app
      - app=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_REGION=${_REGION}
substitutions:
  _REGION: us-central1
  _REPO: stackforge
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/app:$SHORT_SHA
