/**
 * Profile-first locked base files — QA readiness.
 *
 * The model still customizes Terraform, but fragile paths (app stubs, Dockerfiles,
 * provider pins, CI skeletons, README) are seeded from known-good content so
 * validators pass consistently across clouds.
 */
import type { GeneratedFile } from '@/types';
import type { ScaffoldProfile, ScaffoldProfileId } from '@/lib/scaffold-spec';
import { getLanguageFromPath } from '@/lib/utils';
import { getMissingPaths } from '@/lib/scaffold-spec';

type BaseFileMap = Record<string, string>;

const EXPRESS_SERVER = `const express = require('express');
const app = express();
const port = Number(process.env.PORT) || 3000;

app.get('/health', (_req, res) => {
  res.status(200).json({ status: 'ok' });
});

app.get('/', (_req, res) => {
  res.status(200).json({ status: 'ok' });
});

app.listen(port, () => {
  console.log(\`listening on \${port}\`);
});
`;

const EXPRESS_PACKAGE_JSON = `{
  "name": "stackforge-health-stub",
  "version": "1.0.0",
  "private": true,
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "test": "node -e \\"require('http').get('http://127.0.0.1:'+(process.env.PORT||3000)+'/health',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\\""
  },
  "dependencies": {
    "express": "4.18.2"
  }
}
`;

const EXPRESS_PACKAGE_LOCK = `{
  "name": "stackforge-health-stub",
  "version": "1.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "stackforge-health-stub",
      "version": "1.0.0",
      "dependencies": {
        "express": "4.18.2"
      }
    },
    "node_modules/express": {
      "version": "4.18.2",
      "resolved": "https://registry.npmjs.org/express/-/express-4.18.2.tgz",
      "integrity": "sha512-5/PsL6iGPdfQ/lKM1UuielYgv3BUoJfz1aUw1/lW9k8aAoG2eP+/M1rU7M3sW9A+5q5rLJbU9nN5uSYw==",
      "license": "MIT"
    }
  }
}
`;

const NODE_DOCKERFILE_APP = `# hadolint ignore=DL3018
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
ENV PORT=3000
EXPOSE 3000
USER node
CMD ["node", "server.js"]
`;

const FASTAPI_MAIN = `from fastapi import FastAPI

app = FastAPI(
    title="Health stub",
    description="Minimal health-check stub for infrastructure scaffolds.",
    version="0.1.0",
)


@app.get("/")
async def root():
    return {"status": "ok"}


@app.get("/health")
async def health():
    return {"status": "ok"}
`;

const FASTAPI_REQUIREMENTS = `fastapi==0.115.6
uvicorn[standard]==0.34.0
`;

const PYTHON_DOCKERFILE = `# hadolint ignore=DL3008
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=8080
EXPOSE 8080
USER nobody
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
`;

const GO_MAIN = `package main

import (
	"encoding/json"
	"net/http"
	"os"
)

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	http.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	http.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	})
	_ = http.ListenAndServe(":"+port, nil)
}
`;

const GO_MOD = `module stackforge-health-stub

go 1.22
`;

const GO_SUM = ``;

const GO_DOCKERFILE = `# hadolint ignore=DL3008
FROM golang:1.22-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app .

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/app /app
ENV PORT=8080
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app"]
`;

const README_STUB = (title: string) => `# ${title}

Reviewable starting scaffold generated by StackForge (Enlight Labs).

This is **not** drop-in production code. Validate with the in-app Scaffold checks
(terraform / hadolint / actionlint / helm), review IAM and secrets, then customize
before provisioning.

## Includes

- Terraform infrastructure
- CI/CD pipeline skeleton
- Container build + minimal \`/health\` stub (not a full application)
`;

const TF_AWS_VERSIONS = `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.84"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
`;

const TF_AWS_VARIABLES = `variable "aws_region" {
  type        = string
  description = "AWS region"
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Project name prefix"
  default     = "stackforge"
}

variable "environment" {
  type        = string
  description = "Environment name (e.g. staging)"
  default     = "staging"
}

variable "container_port" {
  type        = number
  description = "Container listen port"
  default     = 3000
}

variable "image_tag" {
  type        = string
  description = "Container image tag deployed by CI"
  default     = "latest"
}
`;

const TF_GCP_VERSIONS = `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}
`;

const TF_GCP_VARIABLES = `variable "project_id" {
  type        = string
  description = "GCP project ID"
}

variable "region" {
  type        = string
  description = "GCP region"
  default     = "us-central1"
}

variable "service_name" {
  type        = string
  description = "Cloud Run service name"
  default     = "stackforge-api"
}

variable "image_tag" {
  type        = string
  description = "Container image tag"
  default     = "latest"
}
`;

const TF_AZURE_VERSIONS = `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`;

const TF_AZURE_VARIABLES = `variable "location" {
  type        = string
  description = "Azure region"
  default     = "eastus"
}

variable "project_name" {
  type        = string
  description = "Project name prefix"
  default     = "stackforge"
}

variable "environment" {
  type        = string
  description = "Environment name"
  default     = "staging"
}
`;

const TF_OCI_VERSIONS = `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }
  }
}
`;

const TF_OCI_VARIABLES = `variable "region" {
  type        = string
  description = "OCI region"
  default     = "ap-mumbai-1"
}

variable "compartment_ocid" {
  type        = string
  description = "Compartment OCID"
}

variable "project_name" {
  type        = string
  description = "Project name prefix"
  default     = "stackforge"
}
`;

const GHA_ECS_DEPLOY = `name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: \${{ vars.AWS_REGION || 'us-east-1' }}
  ECR_REPOSITORY: \${{ vars.ECR_REPOSITORY || 'stackforge' }}
  ECS_CLUSTER_NAME: \${{ vars.ECS_CLUSTER_NAME || 'stackforge' }}
  ECS_SERVICE_NAME: \${{ vars.ECS_SERVICE_NAME || 'stackforge' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image_uri: \${{ steps.set-image-uri.outputs.image_uri }}
      prior_task_def_arn: \${{ steps.get-current-service.outputs.current_task_definition_arn }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image URI output
        id: set-image-uri
        run: |
          IMAGE_URI="\${{ steps.login-ecr.outputs.registry }}/\${{ env.ECR_REPOSITORY }}:\${{ github.sha }}"
          echo "image_uri=\$IMAGE_URI" >> "\$GITHUB_OUTPUT"

      - name: Build and push
        run: |
          docker build -t "\${{ steps.set-image-uri.outputs.image_uri }}" -f app/Dockerfile app
          docker push "\${{ steps.set-image-uri.outputs.image_uri }}"

      - name: Capture prior task definition
        id: get-current-service
        run: |
          CURRENT=\$(aws ecs describe-services --cluster "\$ECS_CLUSTER_NAME" --services "\$ECS_SERVICE_NAME" --query 'services[0].taskDefinition' --output text)
          echo "current_task_definition_arn=\$CURRENT" >> "\$GITHUB_OUTPUT"

      - name: Deploy ECS service
        run: |
          aws ecs update-service \\
            --cluster "\$ECS_CLUSTER_NAME" \\
            --service "\$ECS_SERVICE_NAME" \\
            --force-new-deployment
          aws ecs wait services-stable \\
            --cluster "\$ECS_CLUSTER_NAME" \\
            --services "\$ECS_SERVICE_NAME"

  scaffold_rollback:
    if: failure() && needs.deploy.outputs.prior_task_def_arn != ''
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Rollback note
        run: |
          echo "Rollback to prior task definition if deploy failed."
`;

const GHA_EKS_DEPLOY = `name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: \${{ vars.AWS_REGION || 'us-east-1' }}
  EKS_CLUSTER_NAME: \${{ vars.EKS_CLUSTER_NAME || 'stackforge' }}
  HELM_RELEASE: \${{ vars.HELM_RELEASE || 'app' }}
  HELM_NAMESPACE: \${{ vars.HELM_NAMESPACE || 'default' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "\$EKS_CLUSTER_NAME" --region "\$AWS_REGION"

      - name: Helm upgrade
        run: |
          helm upgrade --install "\$HELM_RELEASE" ./charts/app \\
            --namespace "\$HELM_NAMESPACE" \\
            --create-namespace \\
            --atomic \\
            --wait
`;

const GITLAB_CI = `stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: \$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    - python -c "import main; print('ok')"

build:
  stage: build
  image: google/cloud-sdk:slim
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - gcloud auth configure-docker "\$GCP_REGION-docker.pkg.dev" --quiet
    - docker build -t "\$GCP_REGION-docker.pkg.dev/\$GCP_PROJECT_ID/\$AR_REPO/app:\$IMAGE_TAG" .
    - docker push "\$GCP_REGION-docker.pkg.dev/\$GCP_PROJECT_ID/\$AR_REPO/app:\$IMAGE_TAG"
  rules:
    - if: \$CI_COMMIT_BRANCH == \$CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  script:
    - gcloud run deploy "\$CLOUD_RUN_SERVICE" --image "\$GCP_REGION-docker.pkg.dev/\$GCP_PROJECT_ID/\$AR_REPO/app:\$IMAGE_TAG" --region "\$GCP_REGION" --quiet
  rules:
    - if: \$CI_COMMIT_BRANCH == \$CI_DEFAULT_BRANCH
  when: on_success
`;

const AZURE_PIPELINE = `trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Test
    jobs:
      - job: unit
        steps:
          - script: |
              go test ./...
            displayName: Go test

  - stage: Build
    dependsOn: Test
    jobs:
      - job: build_push
        steps:
          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: \$(imageRepository)
              Dockerfile: Dockerfile
              tags: |
                \$(Build.BuildId)

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: deploy_aca
        steps:
          - script: |
              echo "Deploy Container App revision (replace with az containerapp update)."
            displayName: Deploy note
`;

const HELM_CHART = `apiVersion: v2
name: app
description: StackForge reviewable Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
`;

const HELM_VALUES = `replicaCount: 2

image:
  repository: REPLACE_ME
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  create: true
  annotations: {}
`;

const HELM_DEPLOYMENT = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
`;

const HELM_SERVICE = `apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
`;

const HELM_INGRESS = `{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
`;

const HELM_HELPERS = `{{- define "app.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "app.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name (include "app.name" .) | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}

{{- define "app.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "app.labels" -}}
helm.sh/chart: {{ include "app.chart" . }}
{{ include "app.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "app.selectorLabels" -}}
app.kubernetes.io/name: {{ include "app.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{- define "app.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "app.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
`;

/** Outputs must NOT reference undefined resources — that fails terraform validate. */
const SAFE_TF_OUTPUTS = `output "scaffold_note" {
  description = "Reviewable StackForge scaffold — replace with real outputs after resources exist."
  value       = "ok"
}
`;

const HELM_HPA = `{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
`;

const TF_PLACEHOLDER = (note: string) => `# ${note}
# StackForge seeds this path so the file set is complete.
# The generator / completion pass should replace this with real resources.
# Keep provider pins in versions.tf and inputs in variables.tf.
`;

/** Paths that must always use locked content (overwrite model hallucinations). */
export const FORCE_STUB_PATHS = new Set([
  'app/server.js',
  'app/package.json',
  'app/package-lock.json',
  'app/Dockerfile',
  'main.py',
  'requirements.txt',
  'main.go',
  'go.mod',
  'Dockerfile',
  // CI skeletons — model often invents actionlint/ECS bleed failures
  '.github/workflows/deploy.yml',
  '.gitlab-ci.yml',
  'azure-pipelines.yml',
  // Helm helpers — missing templates fail helm lint/template
  'charts/app/templates/_helpers.tpl',
  'charts/app/Chart.yaml',
]);

function awsEcsBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_AWS_VERSIONS,
    'terraform/variables.tf': TF_AWS_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('AWS ECS entrypoint — VPC/ECS/ALB may live in sibling files'),
    'terraform/vpc.tf': TF_PLACEHOLDER('VPC + subnets'),
    'terraform/ecs.tf': TF_PLACEHOLDER('ECS cluster / service / task definition'),
    'terraform/alb.tf': TF_PLACEHOLDER('ALB + target group (/health)'),
    'terraform/iam.tf': TF_PLACEHOLDER('IAM roles/policies'),
    'terraform/security_groups.tf': TF_PLACEHOLDER('Security groups (no SG cycles)'),
    'terraform/redis.tf': TF_PLACEHOLDER('ElastiCache Redis (optional if unused)'),
    'terraform/cloudwatch.tf': TF_PLACEHOLDER('CloudWatch log group'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.github/workflows/deploy.yml': GHA_ECS_DEPLOY,
    'app/Dockerfile': NODE_DOCKERFILE_APP,
    'app/package.json': EXPRESS_PACKAGE_JSON,
    'app/package-lock.json': EXPRESS_PACKAGE_LOCK,
    'app/server.js': EXPRESS_SERVER,
    'README.md': README_STUB('AWS ECS Fargate Scaffold'),
  };
}

function awsEksBase(): BaseFileMap {
  return {
    'terraform/versions.tf': `${TF_AWS_VERSIONS.replace(
      'required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.84"\n    }\n  }',
      `required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.84"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.23"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }
  }`
    )}`,
    'terraform/variables.tf': TF_AWS_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('EKS cluster + networking'),
    'terraform/iam.tf': TF_PLACEHOLDER('IRSA + node/cluster roles'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.github/workflows/deploy.yml': GHA_EKS_DEPLOY,
    'app/Dockerfile': NODE_DOCKERFILE_APP,
    'app/package.json': EXPRESS_PACKAGE_JSON,
    'app/package-lock.json': EXPRESS_PACKAGE_LOCK,
    'app/server.js': EXPRESS_SERVER,
    'charts/app/Chart.yaml': HELM_CHART,
    'charts/app/values.yaml': HELM_VALUES,
    'charts/app/templates/_helpers.tpl': HELM_HELPERS,
    'charts/app/templates/deployment.yaml': HELM_DEPLOYMENT,
    'charts/app/templates/service.yaml': HELM_SERVICE,
    'charts/app/templates/ingress.yaml': HELM_INGRESS,
    'charts/app/templates/hpa.yaml': HELM_HPA,
    'charts/app/templates/serviceaccount.yaml': `{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
`,
    'README.md': README_STUB('AWS EKS + Helm Scaffold'),
  };
}

function gcpCloudRunBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_GCP_VERSIONS,
    'terraform/variables.tf': TF_GCP_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('Cloud Run + Artifact Registry (construct image URL; no repository_url)'),
    'terraform/network.tf': TF_PLACEHOLDER('VPC + private service networking for Cloud SQL'),
    'terraform/database.tf': TF_PLACEHOLDER('Cloud SQL (deletion_protection; private IP complete)'),
    'terraform/iam.tf': TF_PLACEHOLDER('Service accounts + IAM (single data.google_project)'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.gitlab-ci.yml': GITLAB_CI,
    Dockerfile: PYTHON_DOCKERFILE,
    'requirements.txt': FASTAPI_REQUIREMENTS,
    'main.py': FASTAPI_MAIN,
    'README.md': README_STUB('GCP Cloud Run Scaffold'),
  };
}

function azureContainerAppsBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_AZURE_VERSIONS,
    'terraform/variables.tf': TF_AZURE_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('Resource group'),
    'terraform/network.tf': TF_PLACEHOLDER('VNet / subnets'),
    'terraform/database.tf': TF_PLACEHOLDER('PostgreSQL Flexible Server'),
    'terraform/key_vault.tf': TF_PLACEHOLDER('Key Vault'),
    'terraform/identity.tf': TF_PLACEHOLDER('Managed identity'),
    'terraform/container_apps.tf': TF_PLACEHOLDER('Container Apps environment + app'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    'azure-pipelines.yml': AZURE_PIPELINE,
    Dockerfile: GO_DOCKERFILE,
    'go.mod': GO_MOD,
    'go.sum': GO_SUM || '\n',
    'main.go': GO_MAIN,
    'README.md': README_STUB('Azure Container Apps Scaffold'),
  };
}

function oracleOkeBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_OCI_VERSIONS,
    'terraform/variables.tf': TF_OCI_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('OKE cluster + node pool'),
    'terraform/network.tf': TF_PLACEHOLDER('VCN / NSGs'),
    'terraform/iam.tf': TF_PLACEHOLDER('Dynamic groups / policies'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.github/workflows/deploy.yml': `name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Note
        run: |
          echo "Configure OCI CLI + kubectl against OKE, then helm upgrade."
`,
    'app/Dockerfile': NODE_DOCKERFILE_APP,
    'app/package.json': EXPRESS_PACKAGE_JSON,
    'app/package-lock.json': EXPRESS_PACKAGE_LOCK,
    'app/server.js': EXPRESS_SERVER,
    'charts/app/Chart.yaml': HELM_CHART,
    'charts/app/values.yaml': HELM_VALUES,
    'charts/app/templates/_helpers.tpl': HELM_HELPERS,
    'charts/app/templates/deployment.yaml': HELM_DEPLOYMENT,
    'charts/app/templates/service.yaml': HELM_SERVICE,
    'charts/app/templates/ingress.yaml': HELM_INGRESS,
    'charts/app/templates/hpa.yaml': HELM_HPA,
    'README.md': README_STUB('Oracle OKE Scaffold'),
  };
}

function azureAksBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_AZURE_VERSIONS,
    'terraform/variables.tf': TF_AZURE_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('AKS cluster'),
    'terraform/network.tf': TF_PLACEHOLDER('VNet / subnets for AKS'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.github/workflows/deploy.yml': `name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Note
        run: |
          echo "az aks get-credentials + helm upgrade --install"
`,
    'app/Dockerfile': NODE_DOCKERFILE_APP,
    'app/package.json': EXPRESS_PACKAGE_JSON,
    'app/package-lock.json': EXPRESS_PACKAGE_LOCK,
    'app/server.js': EXPRESS_SERVER,
    'charts/app/Chart.yaml': HELM_CHART,
    'charts/app/values.yaml': HELM_VALUES,
    'charts/app/templates/_helpers.tpl': HELM_HELPERS,
    'charts/app/templates/deployment.yaml': HELM_DEPLOYMENT,
    'charts/app/templates/service.yaml': HELM_SERVICE,
    'charts/app/templates/ingress.yaml': HELM_INGRESS,
    'charts/app/templates/hpa.yaml': HELM_HPA,
    'README.md': README_STUB('Azure AKS + Helm Scaffold'),
  };
}

function gcpGkeBase(): BaseFileMap {
  return {
    'terraform/versions.tf': TF_GCP_VERSIONS,
    'terraform/variables.tf': TF_GCP_VARIABLES,
    'terraform/main.tf': TF_PLACEHOLDER('GKE cluster (prefer Autopilot or release_channel — not both)'),
    'terraform/network.tf': TF_PLACEHOLDER('VPC for GKE'),
    'terraform/iam.tf': TF_PLACEHOLDER('Workload Identity / GSA (single data.google_project)'),
    'terraform/outputs.tf': SAFE_TF_OUTPUTS,
    '.github/workflows/deploy.yml': `name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Note
        run: |
          echo "gcloud container clusters get-credentials + helm upgrade --install"
`,
    'app/Dockerfile': NODE_DOCKERFILE_APP,
    'app/package.json': EXPRESS_PACKAGE_JSON,
    'app/package-lock.json': EXPRESS_PACKAGE_LOCK,
    'app/server.js': EXPRESS_SERVER,
    'charts/app/Chart.yaml': HELM_CHART,
    'charts/app/values.yaml': HELM_VALUES,
    'charts/app/templates/_helpers.tpl': HELM_HELPERS,
    'charts/app/templates/deployment.yaml': HELM_DEPLOYMENT,
    'charts/app/templates/service.yaml': HELM_SERVICE,
    'charts/app/templates/ingress.yaml': HELM_INGRESS,
    'charts/app/templates/hpa.yaml': HELM_HPA,
    'README.md': README_STUB('GCP GKE + Helm Scaffold'),
  };
}

const BASES: Record<ScaffoldProfileId, () => BaseFileMap> = {
  'aws-ecs-express': awsEcsBase,
  'aws-eks-helm': awsEksBase,
  'gcp-fastapi-cloudrun': gcpCloudRunBase,
  'azure-go-container-apps': azureContainerAppsBase,
  'oracle-oke-helm': oracleOkeBase,
  'azure-aks-helm': azureAksBase,
  'gcp-gke-helm': gcpGkeBase,
};

export function getProfileBaseFiles(profileId: ScaffoldProfileId): BaseFileMap {
  const factory = BASES[profileId];
  return factory ? factory() : {};
}

export interface MergeLockedBaseOptions {
  /** Fill required paths that the model omitted (default true). */
  fillMissing?: boolean;
  /** Overwrite fragile stub paths even if the model emitted them (default true). */
  forceStubs?: boolean;
}

/**
 * Merge locked profile base files into the generated set.
 * Returns the merged list and which paths were seeded.
 */
export function mergeLockedBaseFiles(
  files: GeneratedFile[],
  profile: ScaffoldProfile,
  options: MergeLockedBaseOptions = {}
): { files: GeneratedFile[]; seeded: string[] } {
  const fillMissing = options.fillMissing !== false;
  const forceStubs = options.forceStubs !== false;
  const base = getProfileBaseFiles(profile.id);
  if (Object.keys(base).length === 0) {
    return { files, seeded: [] };
  }

  const byPath = new Map<string, GeneratedFile>();
  for (const f of files) byPath.set(f.path, f);

  const seeded: string[] = [];
  const missing = fillMissing
    ? getMissingPaths(files, [...profile.requiredPaths])
    : [];

  for (const [path, content] of Object.entries(base)) {
    const exists = byPath.has(path);
    const shouldForce = forceStubs && FORCE_STUB_PATHS.has(path);
    const shouldFill = missing.includes(path) || (!exists && fillMissing);
    // Also fill placeholder-only TF when path exists but is empty
    const existing = byPath.get(path);
    const emptyExisting = exists && !(existing?.content || '').trim();

    if (!shouldForce && !shouldFill && !emptyExisting) continue;

    byPath.set(path, {
      path,
      language: getLanguageFromPath(path),
      content,
      description: shouldForce
        ? 'Locked health stub / base (profile-first)'
        : 'Locked base file (profile-first seed)',
    });
    seeded.push(path);
  }

  return { files: Array.from(byPath.values()), seeded };
}
